### ISSUE TITLE
Ban approval messages removes underscores causing broken image links

### ISSUE THREAD

**Issue by Gvistic** [misterveiga/cds#77]
**Describe the bug**
If a ban request includes underscore's "_", and the bot approves the request the ban message will exclude underscores. Thus if a link requires an underscore the link would not properly work. 

**To Reproduce**
1. Create a ban request that includes underscores.
2. Approve the ban request
3. Observe that the bot did not include the underscores in the ban execution.

**Comment by tyler-hawkins** [comment]
Just some additional information, this is happening because [`getContentStripped()`](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Message.html#getContentStripped()) is being called on the Message reacted to.
It removes markdown formatting (`_` included) from the string in order to prevent the message from retaining any potentially unwanted formatting. I wonder if we could replace this with [`getContentRaw()`](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Message.html#getContentRaw()) to preserve the underscores.

**Comment by Gvistic** [comment]
Makes sense, yeah we could use getContentRaw() then a regex to remove every other markdown formatting besides underscores, "*, **, ~~, ||"

**Comment by TheMadKingNoah** [comment]
This item is solved
